-- Database model
DROP DATABASE IF EXISTS Chatbot;

CREATE DATABASE Chatbot;

USE Chatbot;

CREATE TABLE messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(20),
  content VARCHAR(300),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);